### ISSUE TITLE
Move settings and extensions properties to vscode namespace

### ISSUE THREAD

**Issue by chrmarti** [devcontainers/spec#1]
These VS Code-specific properties are currently top-level. The proposal is to introduce a `vscode` property for VS Code-specific configuration and move these two properties there.

We can copy the properties in the schema, keeping the old properties as 'deprecated' for compatibility.

One open question is how we can include runtime-specific parts of the JSON schema. For those runtimes we know of, we can reference or inline the schema. For now I suggest to keep these properties in the same schema file.

Interestingly settings and extensions also apply to Codespaces which already has a `codespaces` property for its own configuration.

/cc @bamurtaugh @Chuxel @jkeech

**Comment by chrmarti** [comment]
Doing this in 2 stages will allow the support for the new properties to roll out before they become used more widely:
- [ ] February
  - [ ] Add "vscode" property with "extensions" and "settings" subproperties to implementation and schema.
  - [ ] Show a warning when the old and the new property (both "extensions" or both "settings") are used in the same devcontainer.json.
- [ ] March
  - [ ] Update definitions in vscode-dev-containers to use the new properties.
  - [ ] Prefer the new properties when editing by UI command (only 2 cases).

At a future point we might want offer a code action to move the old properties over to the new properties (e.g., when there are more of them). No need to break existing configurations though.

For the devcontainer-features.json we can deprecate the old properties in the schema (but still read them) and start using the new ones.

"customizations" I propose to defer until we have an actual user/customer for it.

**Comment by Chuxel** [comment]
@chrmarti Given our intent to have this be an open spec, I think including a `customizations` property will be important. We do not want adoption of the format to be slowed by a perception that there is no place for other tools while they experiment or add provisional support for the format.

**Comment by bamurtaugh** [comment]
> I worry about name conflicts if it's a "free for all" at the top level. Perhaps we should describe this in contributing.md?

Documenting `customizations` in `contributing.md` makes sense to me. I assume we'd want to wait to describe it until it's actually implemented (not just an fyi right now, so that users don't try to use it already). Unless we wanted to give a more forward look and mention it right now (perhaps linking to this issue; folks who get to this repo may be interested in `How can I contribute my own subproperties`), then update `contributing.md` once it's actually implemented?

**Comment by Chuxel** [comment]
Yeah, I was thinking once we've finalized this proposal.

**Comment by chrmarti** [comment]
Adding `customizations` to the check list above. 👍

I think of `customizations` as something mainly other tools (building on top of the reference or some other implementation) would use (maybe we could use it for temporary explorations). It will be a JSON object with no properties in the schema, but additional properties allowed. We can request tools pick a sufficiently distinctive property name or, more restrictive, a domain name they own (e.g., `"gitpod"` vs. `"gitpod.io"`) to group their custom properties in a JSON object under `customizations`.

**Comment by chrmarti** [comment]
Getting this ready for the February release as proposed above. Let me know if this needs further consideration before we can publish it in a stable release.

**Comment by bamurtaugh** [comment]
I added ` Document `customizations` in `contributing.md`` to the checklist for March above - let me know if folks have other thoughts (on timing, where to document, wording).

**Comment by chrmarti** [comment]
Available with Remote-Containers 0.223.0 (pre-release).

**Comment by jkeech** [comment]
One thing that is important in my mind is to not have a set of first-party/official products that are treated differently in the schema with a separate section for "unofficial" tools. As an open specification, each tool/product that uses devcontainer.json should have an equal playing field with respect to where and how they can extend the devcontainer.json schema for their product-specific customizations.

In order to support this, I would propose that we do not have top-level `codespaces` and `vscode` blocks in the schema with everything else under `customizations`. We could instead have `codespaces` and `vscode` under `customizations`.

```json
{
    "customizations": {
        "vscode": {          
        },
        "codespaces": {
        },
        "gitpod": {
        },
        "someOtherProduct": {
        },
    }
}
```

**Comment by chrmarti** [comment]
My main argument for products running dev containers getting their own top-level property is simplicity of the format. Any such product could ask to be included there, maybe we would require a JSON schema we can reference. Other kinds of tools would remain under customizations which can be self-serviced without us doing anything.

**Comment by jkeech** [comment]
I feel like it's not a great experience to have an official/unofficial split. A few reasons:
1) It gives the appearance that some tools are treated specially and other tools are not welcome or as free to adopt this specification and extend it for their needs
1) Every tool is going to want to be in the special set of official ones, and I don't think we should be the arbiters of which ones are allowed or are "good enough" to be in the official set
1) If you start an unofficial one and later switch to be official, it requires all of your users to alter their devcontainer.json files to use a different property name/location. And then the tool needs to build back-compat code to read from both locations, etc.

The same thing is true for the presentation of published definitions -- I don't want us to have an official set and an unofficial set. Instead, we should just say who the publisher is and let the user decide whether they trust that publisher or not. That follows the verified publisher pattern of many other registries and doesn't result in having a two-tiered system where some things are more favored than others.

**Comment by Chuxel** [comment]
Another test here - since I had a similar reaction - if we had 27 tools and services adopt devcontainer.json, would we want 27 unique top-level properties? I worry that would obscure the common ones.

**Comment by chrmarti** [comment]
My proposal is to only allow products that run dev containers ("dev container runtimes") to have a top-level property. I don't expect there to be 27 of those.

I understand the concerns of the top-level properties being perceived as being treated special and that moving from customizations to top-level might be seen as an unnecessary migration step (I imagine products would maintain backwards compatibility, so it's maybe not a big a problem). The community's perception also depends on how we communicate the existence of the top-level properties and how we weigh that against the added complexity of everything going under "customizations".

In both cases we can reference other products' (including our own) JSON schema. I would avoid the ambiguity of allowing "customizations.vscode" as an alternative to "customizations" with subproperties.

As we are approaching the Remote-Containers release next week, could we have a quick vote on where we want to go:
1) Top-level properties for products running dev containers ("codespaces", "gitlab", "vscode").
2) All tools and products properties go under "customizations" ("customizations"."codespaces").
3) Needs more discussion. Defer until next release.
4) Other proposals.

I'm good with 1) or 2), preferring 1).

**Comment by chrmarti** [comment]
Others have mentioned:
- `gitpod.yml` has a top-level `vscode` property: https://www.gitpod.io/docs/references/gitpod-yml. Top-level properties for dev container runtimes are more user-friendly because they are easier to read.
- A variation on `"customizations"` would be top-level properties with the reserved `x-` prefix. This could work with 1) and 2). I guess `x-` is short, while `"customizations"` is more explicit and more in line with what we already have. (E.g.: `"x-mytool": { "option1": "value1", ... }`.)

**Comment by bamurtaugh** [comment]
@chrmarti I like options 1) or 2) above. 

> My proposal is to only allow products that run dev containers ("dev container runtimes") to have a top-level property. I don't expect there to be 27 of those.

I think this makes a lot of sense, but could it be a nuance users won't recognize?

> A variation on "customizations" would be top-level properties with the reserved x- prefix. This could work with 1) and 2). 

Is this `x-` prefix common practice? Would the `x-` go away for tools that have been formally added and are considered "top-level," or would all tools have an `x-`?

**Comment by jkeech** [comment]
I don't have a strong opinion about top-level vs under customizations. My vote is just to have everything be at the same level, regardless of where that level is, and not have some at the top level and some under a different node.

>A variation on "customizations" would be top-level properties with the reserved x- prefix. 

I don't prefer the `x-` prefix. If we want them at the top level, I think I'd rather just see `vscode`, `codespaces`, `gitpod`, etc directly.

**Comment by chrmarti** [comment]
The main reason for having `"customizations"` in addition to top-level properties is that the community can easily self-service `"customizations"` by picking a unique property name for their tool to group its configuration values under. The same can be achieved by reserving top-level properties with the `x-` (or other) prefix for tools. (E.g., swagger uses `x-` as prefix: https://swagger.io/docs/specification/openapi-extensions/.)
```
{
	"vscode": {
		"extensions": [],
		"settings": {},
		"devPort": 3000
	},
	"codespaces": {
	},
	"x-example.com": {
		"foo": "bar"
	},
	"x-foobar": {
		// ...
	}
}
```

I'm still leaning towards using `"customizations"` in combination with top-level properties for tools like `gitpod`, `codespaces` and `vscode` (for its simplicity to the user). I understand the concern about the perception having two tiers, but we can make it clear in the documentation that we offer to reserve top-level properties for other dev container runtimes.

**Comment by Chuxel** [comment]
Yeah - an example scenario that `customizations` (or `x-`) can help with is things like @lostintangent's exploration in this extension: https://marketplace.visualstudio.com/items?itemName=lostintangent.workspace-layout 

Rather than a top level `workspaces` property, this could be under a "customizations.lostintangent.workspace-layout" property for exploration purposes. At some point, a proposal could come in to move it to a common location. 

No matter what, we need a process to "reserve" a name to avoid conflicts once it's in the broader schema. But many formats allow for customization beyond that with these types of things in mind.

**Comment by jkeech** [comment]
> But many formats allow for customization beyond that with these types of things in mind. In many cases you may want an initial implementation before you even make a formal proposal to try out the idea... or it may just be too narrowly applicable to raise it. Either way, having a spot for this kind of thing is goodness.

I don't think we need to have _separate_ spots for this though. Why not have a pattern where everything fits into the same place, and then you can officially reserve one of those names in the schema if you think you need to due to potential collisions? That way you don't have a breaking change if you later decide to reserve a name once your tool/extension gets popular enough.

For instance, if everything was under `customizations` (or top-level; doesn't matter for this example), the extension referenced above could start using `customizations: { "lostintangent.workspace-layout" }` today. Then if the author wanted to make that name reservation more official to prevent collisions with other tools, they could open a PR to reserve the `lostintangent.workspace-layout` key. Users who use that config in `devcontainer.json` would not need to change the config in their repos when the name reservation became official, nor would the extension need to build backwards-compatibility support to check for both the official and unofficial location (since they are the same). The act of reserving a name and making it official would only codify existing patterns instead of requiring people to adopt new patterns.

**Comment by chrmarti** [comment]
One reason to not allow top-level properties without prefix being introduced by tools themselves is that we then can't distinguish typos from legitimate customizations during validation. So if we want to allow tools to go from an ad-hoc property to a reserved property in-place, we would have to use `"customizations"`.

Do we have good examples for customizations that are not dev container runtimes? E.g., the workspace layout is about the UI and not about the dev container, so maybe that should go into a different config file.

**Comment by chrmarti** [comment]
Moving the schema change to the next milestone to allow for more time for the discussion here as we are approaching the VS Code release which would include the update. (Moving the schema to this repository is tracked in https://github.com/microsoft/dev-container-spec/issues/14.)

**Comment by chrmarti** [comment]
In meeting yesterday we agreed that having everything under a single top-level property (like `customizations`) would make it clear where other tools' properties should go and avoid the impression that there might be a bias towards supporting VS Code. We discussed using a shorter property name than `customizations` and came up with `tools`, `plugins` and `addons`, but did not decide on which one yet to allow for additional ideas.

**Comment by sinedied** [comment]
I'm not sure that wanting to limit top-level properties to only official ones, and put aside extra/specific properties under `customizations` or `product` or whatever is a good move. Schema validation could check known official properties, while still allowing anyone to add whatever needed in the top-level properties.

A good example of that are `package.json` files in the Node.js ecosystem: anyone/any tool can add top levels properties, and a lot of tooling (prettier, eslint and more) take advantage of that. This makes things both simpler and more open to future extensions that may become de-facto standard before moving at some point in the spec, rather than purposely distinguish what's official and what's not, making it harder for open experiments.

**Comment by chrmarti** [comment]
@sinedied Not sure I understand your comment correctly, but to clarify: Both established and new or ad-hoc customizations would go under `"customizations"` (or some shorter name). So VS Code's properties would be grouped under `"customizations"`.`"vscode"`, just like any other, e.g., `"customizations"`.`"gitpod"`.

The only remaining top-level properties would be the ones common to all dev containers independently of the IDE/editor they run with. (Like `"name"`, `"image"`, "dockerComposeFile"`, and so on.)

**Comment by sinedied** [comment]
That's exactly what I'm calling out, why not drop the `"customizations"` extra level and allow any extra property at the top level? I see little value in grouping them in an extra level.

If you're worried about name conflicts, I've yet to heard of one in `package.json` files yet the same principle applies: you're free to add whatever property you need in your json, the 3rd party tools will read whatever they need to.

The benefit of that approach, besides simplicity is that there would be no need to "reserve" top level properties, leaving out the difficult question of who has the rights to add top level properties and who doesn't, making the spec truly open in that regard.

**Comment by chrmarti** [comment]
We will add more top-level properties for the open spec in the future and want to avoid having these clash with custom properties other editors and IDEs might have added since.

Not sure the package.json is used the same way, e.g., a package.json for a VS Code extension is usually only used for that extension and nothing else, so chances for property collisions between tools are low. We want the same devcontainer.json to support multiple editors and IDEs and that is different from what I have seen with the package.json.

**Comment by chrmarti** [comment]
Any opinions on `customizations` vs. `tools`, `plugins` or `addons`?

`customizations` is nicely neutral and to the point.

**Comment by sinedied** [comment]
What about `extras`? It's shorter, still neutral and implies something that doesn't belong to the base schema.

**Comment by bamurtaugh** [comment]
While I like the brevity of something like `extras`, I like `customizations` as it already signifies in the name this will be a way to further customize your dev container.

**Comment by jkeech** [comment]
I'll throw one more in the mix: `configuration` or the abbreviated `config`. I think I like `configuration` the best followed by `customization`/`customizations`. Within the configuration block, you can provide configuration options/settings for various tools that leverage devcontainer.json (vscode, codespaces, etc).

```
"configuration": {
    "vscode": { ... },
    "codespaces": { ... },
    ...
}
```

**Comment by Chuxel** [comment]
Yeah `settings` would be a good name, but that's already used for vscode settings prior to this change, so that would create a ton of confusion. Tho long, these are basically `namespaces` for other properties that may even originate from a different json schema - they are also `other` properties not in the common schema.

**Comment by chrmarti** [comment]
In further discussions we realized that `customizations` might be the best of the discussed options because it neither includes nor excludes specific usages. The way we looked at it, the other discussed names seemed to include some sort expectation towards their use and we want to avoid that. I now plan to implement this as `customizations`.

**Comment by bamurtaugh** [comment]
As this is in finalization, should we work on the action items [here](https://github.com/devcontainers/spec/issues/1#issuecomment-1036612267) (i.e. updating definitions and docs)?

**Comment by chrmarti** [comment]
We moved the timeline by another month (updated the above comment). So we now publish and deploy the support for the new properties in April and can start using them by default in May.

**Comment by bamurtaugh** [comment]
We've addressed the first item in the [May checklist](https://github.com/devcontainers/spec/issues/1#issuecomment-1036612267) (updating samples and docs).

Have we addressed the second item: `Prefer the new properties when editing by UI command (only 2 cases)`?

Item 3 mentions documenting in `contributing.md`. Looking at [`contributing.md`](https://github.com/devcontainers/spec/blob/main/contributing.md), and I opened the following PR: https://github.com/devcontainers/spec/pull/34. Ed is also documenting `customizations` in the [initial version of the spec](https://github.com/devcontainers/spec/pull/33).

**Comment by chrmarti** [comment]
Doing `Prefer the new properties when editing by UI command (only 2 cases)` now.

Looks like we are done. Closing this issue. Thanks everyone!
