### ISSUE TITLE
Access host chrome from vscode devcontainer

### ISSUE THREAD

**Issue by RaviTejaVattem** [devcontainers/spec#266]
I am wondering if there is a way to access the chrome installed on host machine(Mac) from vscode devcontainer?

I have a devcontainer.json file as follows

```json
{
    "name": "Node.js",
    "build": {
        "dockerfile": "Dockerfile"
    },
    "remoteEnv": {
        "TEST": "${localEnv:TEST}",
        "CHROME_BIN": "${containerEnv:PATH}:/Applications/'Google Chrome.app'/Contents/MacOS/'Google Chrome'"
    }
}
```
I want to run jasmine tests from the container which is expecting "CHROME_BIN" env variable which should be a chrome binary.

When I spin-up the container with the above configuration, karma launcher is unable to find chrome(In other words the docker container is unable to locate host machine's chrome with CHROME_BIN variable I set).

BTW I do not want to run chrome in headless mode inside my docker container.

I already asked the same question in [stackoverflow](https://stackoverflow.com/questions/76536083/access-host-chrome-from-vscode-devcontainer) but couldn't get any help.

**Comment by avidal** [comment]
I think that you'd have to leverage the `mounts` property to mount in the Chrome binary, but then you're going to have another problem: the Chrome binary you mount in is built for macOS, not built for Linux, and won't be executable.

And even if you bypass that, you won't be able to see a UI without also doing display forwarding and running an X display server on your host machine.

Finally, I don't think this is the right place to get help for your question. It's about issues related to the *specification* for devcontainers. If you're doing this through VSCode I think the better place is microsoft/vscode-remote-release since that's specifically on the Remote extension and its related extensions (including its implementation of devcontainers).

**Comment by RaviTejaVattem** [comment]
Thanks a lot for the inputs @avidal.
